# restic/tasks/main.yml
---
- name: Install restic
  ansible.builtin.package:
    name: "{{ restic_package_name }}"
    state: present

- name: Ensure group restic group exists
  ansible.builtin.group:
    name: "{{ restic_service_account_group }}"
    state: present

- name: create a service account for restic
  ansible.builtin.user:
    name: "{{ restic_service_account_name }}"
    shell: /usr/sbin/nologin
    group: "{{ restic_service_account_group }}"
    system: true
    create_home: true

- name: Create systemd service from template
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - restic@.service
    - restic@.timer
  notify: enable and start restic timer

- name: Create restic instance directory if it does not exist
  become: true
  ansible.builtin.file:
    path: "{{ restic_service_account_home }}/{{ systemd_instance_name }}"
    state: directory
    mode: '0750'
    owner: root
    group: root

- name: Create .ssh  directory if it does not exist
  become: true
  ansible.builtin.file:
    path: "{{ restic_service_account_home }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ restic_service_account_name }}"
    group: "{{ restic_service_account_group }}"

- name: create restic key id password file
  ansible.builtin.file:
    dest: "{{ restic_service_account_home }}/{{ systemd_instance_name }}/{{ restic_key_id }}"
    state: touch
    mode: '0400'
    owner: root
    group: root

- name: create restic include and exclude files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ restic_service_account_home }}/{{ systemd_instance_name }}/{{ item }}"
    mode: '0400'
    owner: root
    group: root
  loop:
    - include.file
    - exclude.file
    - restic.env

- name: Create systemd user service from template
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/user/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - systemd-desktop-notifier@.service
    - systemd-desktop-notifier@.timer
  when: enable_desktop_notifications | default(false)
  notify: enable and start systemd-desktop-notifier timer

- name: copy restart-service script
  ansible.builtin.copy:
    src: files/systemd-desktop-notifier.sh
    dest: /usr/local/bin/systemd-desktop-notifier.sh
    owner: root
    group: root
    mode: 0755
    force: true
  when: enable_desktop_notifications | default(false)
